Areas/Database/Controllers/DBManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP.NET_CORE_MVC.Models;
using Microsoft.EntityFrameworkCore;

namespace ASP.NET_CORE_MVC.Areas.Database.controllers
{
    [Area("Database")]
    [Route("/database-manage/[action]")]
    public class DBManageController : Controller
    {
        private readonly AppDBContext _dbcontext;
        public DBManageController(AppDBContext dBContext)
        {
            _dbcontext = dBContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [TempData]
        public string StatusMessage{get;set;}
        [HttpGet]
        public IActionResult DeleteDb()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDbAysnc()
        {
            var success = await _dbcontext.Database.EnsureDeletedAsync();
            StatusMessage = success ? "Xóa database thành công" : "Không xóa duoc";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Migrate()
        {
            await _dbcontext.Database.MigrateAsync();
            StatusMessage = "Cập nhập database thành công";
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/PlanetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.IO;
using ASP.NET_CORE_MVC.Services;
using System.Linq;

namespace ASP.NET_CORE_MVC.Controllers
{
    //Thiết lập route cho hệ mặt trời
    //Thiết lập action trong route của controller thì kh cần thiếp lập route cho các action trong controller
    [Route("he-mat-troi/[action]")]
    public class PlanetController : Controller
    {
        private readonly PlanetSerivce _planetServices;
        private readonly ILogger<PlanetController> _logger;
        public PlanetController(PlanetSerivce planetService, ILogger<PlanetController> logger)
        {
            _planetServices = planetService;
            _logger = logger;
        }
        
        //Nếu thiệt lập dấu '/' trước route url thì sẽ kh kết hợp với route controller => /danh-sach-cac-hanh-tinh.html -> ok
        //custom đường dẫn cho trang index
        [Route("/danh-sach-cac-hanh-tinh.html")]
        public IActionResult Index() //   he-mat-troi/danh-sach-cac-hanh-tinh.html
        {
            return View();
        }

        //route: action
        [BindProperty(SupportsGet = true, Name="action")]
        public string Name{get;set;} //Action ~ PlanetModel



        //Nếu thiết lập route controller thì phải thêm route vào các action để truy vấn được action vd: Route("ten-ket-hop"))
        public IActionResult English1()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }
        public IActionResult English2()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }
        public IActionResult English3()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }
        public IActionResult English4()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }
        public IActionResult English5()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }

        //Chỉ truy cập bằng phương thức GET với địa chỉ này
        [HttpGet("/English6.html")]
        public IActionResult English6()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }

        //order là độ ưu tiên cho thẻ asp-action phát sinh ra url (1 trong route)
        //Name dùng để phát sinh route url
        [Route("sao/[action]", Order=3, Name="english7-1")]//sao/English7
        [Route("sao/[controller]/[action]",Order=2, Name="english7-2")] // * sao/Planet/English7
        [Route("[controller]-[action].html",Order=1, Name= "english7-3")]//Planet-English7.html
        public IActionResult English7()
        {
            var planet = _planetServices.Where(x=>x.Name == Name).FirstOrDefault();
            return View("Detail",planet);
        }

        //controller, action, area => {controler} [action] [area]

        [Route("hanhtinh/{id:int}")] //Ràng buộc id - sẽ không truy cập theo địa chỉ endpoints định nghĩa trong startup nữa
        public IActionResult PlanetInfo(int id)
        {
            var planet = _planetServices.Where(x=>x.Id == id).FirstOrDefault();

            return View("Detail",planet);
        }
    }

}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}


@if(!string.IsNullOrEmpty(message))
{
    <div class="alert alert-warning fade show" role="alert">
        <strong>@message</strong>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_CORE_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET_CORE_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Privacy</a>
                        </li>
                        
                    </ul>
                    <partial name="_MenuManagePartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP.NET_CORE_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
<div class="dropdown">
    <a href="#" id="managedropdownmenu" data-toggle="dropdown">Manage</a>
    <div class="dropdown-menu" aria-labelledby="managedropdownmenu">
        <a class="dropdown-item" asp-action="Index" asp-controller="DBManage" asp-area="Database">
            Database
        </a>
    </div>
</div>